apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1
  version: "1.29"  # Use the latest Kubernetes version

managedNodeGroups:
  - name: expense
    instanceTypes: ["m5.large", "c5.large"]
    desiredCapacity: 3
    spot: true
    minSize: 1
    maxSize: 5  # Allow auto-scaling if Spot Instances are unavailable
